#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 <command>" 1>&2
	echo 1>&2
	echo "libeatmydata is a LD_PRELOAD library to disable fsync and friends." 1>&2
	exit 1
fi

/usr/bin/env LD_PRELOAD=__LIBDIR__/libeatmydata.so $@
